version: '3.8'

services:
  kitsu:
    container_name: cgwire-kitsu
    image: emberlightvfx/kitsu-for-docker:latest
    depends_on:
      - zou-app
      - zou-event
      - zou-jobs
    ports:
      - '8800:80'
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - 'kitsu:/opt/kitsu'
    networks:
      - cgwire

  zou-app:
    container_name: cgwire-zou-app
    image: emberlightvfx/zou-for-docker:latest
    depends_on:
      - db
    volumes:
      - 'previews:/opt/zou/previews'
      - 'tmp:/tmp/zou'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cgwire
    command: >
      sh -c "/download_zou.sh &&
      /init_zou.sh &&
      gunicorn --error-logfile - --access-logfile - -w 3 -k gevent -b :5000 zou.app:app"

  zou-event:
    container_name: cgwire-zou-event
    image: emberlightvfx/zou-for-docker:latest
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cgwire
    command: >
      sh -c "/download_zou.sh &&
      gunicorn --error-logfile - --access-logfile - -w 1 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b :5001 zou.event_stream:app"

  zou-jobs:
    container_name: cgwire-zou-jobs
    image: emberlightvfx/zou-for-docker:latest
    volumes:
      - 'previews:/opt/zou/previews'
      - 'tmp:/tmp/zou'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cgwire
    command: >
      sh -c "/download_zou.sh &&
      rq worker -c zou.job_settings"

  db:
    container_name: cgwire-db-12
    image: postgres:12-alpine
    volumes:
      - 'db:/var/lib/postgresql/data'
      - ./db/pg_ctl.conf:/etc/postgresql/12/main/pg_ctl.conf:ro
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cgwire

  redis:
    container_name: cgwire-redis
    image: redis:alpine
    volumes:
      - 'redis:/data'
    restart: unless-stopped
    networks:
      - cgwire

volumes:
  db:
    name: zou-db-12
  redis:
    name: cgwire-redis
  previews:
    name: cgwire-previews
  tmp:
    name: cgwire-tmp
  kitsu:
    name: cgwire-kitsu

networks:
  cgwire:
    name: cgwire
